<?php

/**
 * @file
 * Contains fullname.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fullname_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fullname module.
    case 'help.page.fullname':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
